[package]
name = "solar-share-meta"
version = "0.0.0"
authors = [ "Louis Travaux",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.solar-share]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.7"
